### ISSUE TITLE
'CAN_D1_D2' was not declared in this scope

### ISSUE THREAD

**Issue by appillustrator** [carloop/carloop-library#2]
Veryfing code using this library in Particle Build fails with this error:

```
carloop/carloop.h:20:38: error: 'CAN_D1_D2' was not declared in this scope
     static constexpr auto CAN_PINS = CAN_D1_D2
```

**Comment by monkbroc** [comment]
Sorry I didn't see your issue here.

You need to tell build to use firmware 0.4.9 or later when compiling the program.
See https://community.carloop.io/t/carloop-demo-program/18/2
