### ISSUE TITLE
Compatibility with Particle electron firmware version 0.7.0

### ISSUE THREAD

**Issue by eron93br** [carloop/carloop-library#7]
Hello all, 

I've updated my particle electron last week to firmware version 0.7.0!

Previously on firmware version 0.6.0 my carloop apps used to run perfectly, but now when I upload any carloop project, even the PID readers, my particle electron starts to flash red and don't run the code.

There is any incompatibility with carloop library and particle electron firmware 0.7???

thanks, this error is very strange :(

**Comment by monkbroc** [comment]
There is a regression bug in particle firmware 0.7.0 that affects Carloop. I made a workaround in the Carloop library. You need to update to the latest version. You can do that in the Web IDE by re-adding the Carloop library.
